#!/bin/bash


/usr/bin/apt update -y
/usr/bin/apt upgrade -y

#testing packges: python3, git, and nginx
/usr/bin/apt install -y python3
/usr/bin/apt install -y git
/usr/bin/apt install -y nginx

#messing with nginx service
systemctl start nginx
systemctl enable nginx
